### ISSUE TITLE
The security configuration does not conform OAS2 specification

### ISSUE THREAD

**Issue by mmartinv** [openshift/assisted-service#1481]
According to the [OAS2 documentation ](https://swagger.io/docs/specification/2-0/authentication/) defining the scope is only valid for '**oauth2**' security definition types. However, [there are scopes](https://github.com/openshift/assisted-service/blob/master/swagger.yaml#L39) defined on '**apiKey**' type:
 ```
securityDefinitions:
  agentAuth:
    type: apiKey
    in: header
    name: X-Secret-Key
  userAuth:
    type: apiKey
    in: header
    name: Authorization
  urlAuth:
    type: apiKey
    in: query
    name: api_key

security:
  - userAuth: [admin, user]
```
