### ISSUE TITLE
Hostprefix should not be required for non OpenshiftSDN / OVNkubernetes networktypes

### ISSUE THREAD

**Issue by ppeereb1** [openshift/assisted-service#5448]
For plugins like Calico which don't use the hostPrefix for anything,
it does not make sense to validate this field and force customers
to set specific values just to pass validation considering the
field is not even used in these plugins.

install-config example:
```
apiVersion: v1
baseDomain: dummy.hostname.com
metadata:
  name: ref3
networking:
  machineNetwork:
    - cidr: 10.10.127.0/24
  clusterNetwork:
    - cidr: 10.128.0.0/14
  serviceNetwork:
    - 172.30.0.0/16
  networkType: Calico
compute:
- name: worker
  hyperthreading: Disabled
  replicas: 6
controlPlane:
  name: master
  hyperthreading: Enabled
  replicas: 3
  platform:
    baremetal: {}
```

Because I did not specify the hostprefix it fails with the following error in the assisted installer:
Invalid Cluster Network prefix: Host prefix, now 0, must be a positive integer.
https://github.com/openshift/assisted-service/blob/master/internal/network/cidr_validations.go#L148

It should only fail for OVN/Openshift SDN networktypes. See similar bugzilla for other installers: https://bugzilla.redhat.com/show_bug.cgi?id=1852112
