### ISSUE TITLE
Support HTTPS URL for HTTPS_Proxy

### ISSUE THREAD

**Issue by MrBr-github** [openshift/assisted-service#6261]
According to the [swagger.yaml](https://github.com/openshift/assisted-service/blob/master/swagger.yaml#L4823) only `http` URL is supported for `https_proxy`
However starting from [Open Shift 4.8](https://docs.openshift.com/container-platform/4.8/networking/enable-cluster-wide-proxy.html) this URL can be `https`. 

Please add support for HTTPS URLs.

```
apiVersion: config.openshift.io/v1
kind: Proxy
metadata:
  name: cluster
spec:
  httpProxy: http://<username>:<pswd>@<ip>:<port> 
  httpsProxy: https://<username>:<pswd>@<ip>:<port> 
  noProxy: example.com 
  readinessEndpoints:
  - http://www.google.com 
  - https://www.google.com
  trustedCA:
    name: user-ca-bundle 
```
