### ISSUE TITLE
Logical bug - missing machine network

### ISSUE THREAD

**Issue by gtomilko** [openshift/assisted-service#7473]
When on the second step "Static network configurations" you switch from form view to yaml there is no place to enter Machine network information. As result you can not finish cluster configuration, get stuck on Networking with 

![Image](https://github.com/user-attachments/assets/001f5ad7-0f7d-4d79-b5d6-63484a4fbea0)

Just suggestion: add "Machine Network" field to "Use advanced networking"

![Image](https://github.com/user-attachments/assets/69f7dded-3aac-44b0-a9a8-2f39b41aea34)

**Comment by rccrdpccl** [comment]
Sorry we have missed this issue. Where do you encounter this issue? How did you deploy assisted installer and [its UI](https://github.com/openshift-assisted/assisted-installer-ui)?

**Comment by gtomilko** [comment]
@rccrdpccl  It was deployed in podman following instructions for http. When you configure static network using yaml there no place to specify machineNetwork

<img width="1900" height="1066" alt="Image" src="https://github.com/user-attachments/assets/af01fb1d-d972-430c-af5b-6e540a72c359" />

as result when you get to Networking page in workflow

<img width="1687" height="864" alt="Image" src="https://github.com/user-attachments/assets/4de963b0-a77e-4947-afb6-63a4577c77a3" />

**Comment by gtomilko** [comment]
Anybody alive?

**Comment by rccrdpccl** [comment]
@gtomilko Is this while running the latest version? Is it the upstream software or the RH distribution?

@rawagner is this issue something we are aware of?

**Comment by rawagner** [comment]
machine network dropdown is populated based on values of cluster's [machineNetworks](https://github.com/openshift/assisted-service/blob/master/swagger.yaml#L5692). Maybe none are reported ?

**Comment by rccrdpccl** [comment]
@gtomilko please provide the following:
* Type of deployment you are running:
  * SaaS on console.redhat.com
  * on-prem ACM/ZTP
  * podman

* Version of the software (if you can try latest version it would be great)

Once you can provide this information we can choose the best path to solve your issue

**Comment by gtomilko** [comment]
@rccrdpccl My installation is on-prem in podman. Here is About screen

<img width="766" height="800" alt="Image" src="https://github.com/user-attachments/assets/6732a315-12c0-47eb-a5e1-786fe1218cc5" />

**Comment by gtomilko** [comment]
Here is my configmap.yml
```
apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  ASSISTED_SERVICE_HOST: 127.0.0.1:8090
  ASSISTED_SERVICE_SCHEME: http
  AUTH_TYPE: none
  DB_HOST: 127.0.0.1
  DB_NAME: installer
  DB_PASS: admin
  DB_PORT: "5432"
  DB_USER: admin
  DEPLOY_TARGET: onprem
  DISK_ENCRYPTION_SUPPORT: "false"
  DUMMY_IGNITION: "false"
  ENABLE_SINGLE_NODE_DNSMASQ: "false"
  HW_VALIDATOR_REQUIREMENTS: '[{"version":"default","master":{"cpu_cores":4,"ram_mib":16384,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":100,"packet_loss_percentage":0},"arbiter":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":1000,"packet_loss_percentage":0},"worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10,"network_latency_threshold_ms":1000,"packet_loss_percentage":10},"sno":{"cpu_cores":8,"ram_mib":16384,"disk_size_gb":100,"installation_disk_speed_threshold_ms":10},"edge-worker":{"cpu_cores":2,"ram_mib":8192,"disk_size_gb":15,"installation_disk_speed_threshold_ms":10}}]'
  IMAGE_SERVICE_BASE_URL: http://192.168.94.28:8888
  IPV6_SUPPORT: "true"
  ISO_IMAGE_TYPE: "full-iso"
  LISTEN_PORT: "8888"
  NTP_DEFAULT_SERVER: ""
  POSTGRESQL_DATABASE: installer
  POSTGRESQL_PASSWORD: admin
  POSTGRESQL_USER: admin
  PUBLIC_CONTAINER_REGISTRIES: 'quay.io,registry.ci.openshift.org'
  SERVICE_BASE_URL: http://192.168.94.28:8090
  STORAGE: filesystem
  OS_IMAGES: '[{"openshift_version":"4.16","cpu_architecture":"x86_64","url":"https://builds.coreos.fedoraproject.org/prod/streams/stable/builds/39.20240322.3.1/x86_64/fedora-coreos-39.20240322.3.1-live.x86_64.iso","version":"39.20240322.3.1"},{"openshift_version":"4.19","cpu_architecture":"x86_64","url":"https://rhcos.mirror.openshift.com/art/storage/prod/streams/c9s/builds/9.0.20250510-0/x86_64/scos-9.0.20250510-0-live-iso.x86_64.iso","version":"9.0.20250510-0"}]'
  RELEASE_IMAGES: '[{"openshift_version":"4.16","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"registry.ci.openshift.org/origin/release:4.16","version":"4.16.0-0.okd","default":false,"support_level":"beta"},{"openshift_version":"4.19","cpu_architecture":"x86_64","cpu_architectures":["x86_64"],"url":"quay.io/okd/scos-release:4.19.0-okd-scos.16","version":"4.19.0-okd-scos.16","default":true,"support_level":"beta"}]'
  ENABLE_UPGRADE_AGENT: "false"
  ENABLE_OKD_SUPPORT: "true"
```

**Comment by gtomilko** [comment]
Here is podman version:
Client:       Podman Engine
Version:      4.9.4-rhel
API Version:  4.9.4-rhel
Go Version:   go1.23.9 (Red Hat 1.23.9-1.module+el8.10.0+23162+9223a61a)
Built:        Wed Jun 25 05:17:23 2025
OS/Arch:      linux/amd64

**Comment by rccrdpccl** [comment]
Thanks for this info.
Can you please share the actual sha used instead of the latest tag, for the assisted components?
Also, could you please share the static network configuration you have been using?

**Comment by gtomilko** [comment]
Here is my static network config for one of the nodes:
```
interfaces:
  - name: eth0
    type: ethernet
    state: up
    mtu: 9000

  - name: eth1
    type: ethernet
    state: up
    mtu: 9000

  - name: bond0
    type: bond
    state: up
    mtu: 9000
    link-aggregation:
      mode: balance-xor
      options:
        miimon: '100'
      ports:
        - eth0
        - eth1
    ipv4:
      enabled: false
    ipv6:
      enabled: false

  - name: bond0.94
    type: vlan
    state: up
    mtu: 9000
    vlan:
      base-iface: bond0
      id: 94
    ipv4:
      enabled: false
    ipv6:
      enabled: false

  - name: br94
    type: linux-bridge
    state: up
    mtu: 9000
    bridge:
      options:
        stp:
          enabled: true
      port:
        - name: bond0.94
    ipv4:
      enabled: true
      address:
        - ip: 192.168.94.43
          prefix-length: 24
      auto-dns: false
      auto-gateway: false
            
    ipv6:
      enabled: false
dns-resolver:
  config:
    server:
      - 192.168.96.5
      - 192.168.98.6
    search:
      - our.tld

routes:
  config:
    - destination: 0.0.0.0/0
      next-hop-address: 192.168.94.1
      next-hop-interface: br94
```
